module.exports = {
	siteURL: process.env.URL || 'http://localhost:8080',
	siteName: "DH Alchemy",
	siteDescription:'A DH Consultancy',
	siteImage: '/assets/images/site/default.png',
	lang: 'en',
	locale: 'en_us',
	authorName: 'the cooperative',
	authorURL: '',
	authorEmail: '',
	twitterSite: '',
	twitterCreator: '',
	address: {
		street: '',
		city: 'Ottawa',
		state: 'ON',
		zip: '',
		phoneDisplay: '',
		phoneCall: '',
		email: 'dhalchemy@craftingdigitalhistory.ca',
	},
}
